[project]
name = "ml-karpathy"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "regex>=2025.11.3",
    "requests>=2.32.5",
    "tiktoken>=0.12.0",
    "torch>=2.9.1",
    "transformers[torch]>=4.57.3",
]
